# Site settings
title: Smart Sparrow
baseurl: "http://considered.design"

# Build settings
markdown: kramdown

# Collections
collections:
  case-studies:
    output: true
    permalink: /case-studies/:path/