# Site settings
title: Considered Design
email: dominic@considered.design
description: > # this means to ignore newlines until "baseurl:"
  I help set and mature design direction in products looking to create longterm value.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://considered.design" # the base hostname & protocol for your site
twitter_username: dominosebastian
github_username:  domseb


# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  notes:
    output: true
    permalink: /notes/:path/

gems:
  - jekyll-assets
  - octopress-autoprefixer
  - jekyll-twitter-plugin
  - jekyll-include-cache

plugins:
  - jekyll-include-cache
  - jekyll-twitter-plugin

navigation:
  - title: work
    url: /work/
  - title: about
    url: /about/
  - title: writing
    url: /writing/
  - title: notes
    url: /notes/
