# Site settings
title: Smart Sparrow
baseurl: "https://www.smartsparrow.com/"

# Build settings
markdown: kramdown

# Collections
collections:
  case-studies:
    output: true
    permalink: /case-studies/:path/

sass:
    style: :compressed
